### ISSUE TITLE
Übersetzung unter Benachrichtigungen bei Android System

### ISSUE THREAD

**Issue by MeiGuddet** [berlinux2016/MIUI11#1]
- **MIUI Version:** 9.9.26
- **Device name:** Mi 9T

**Screenshot/Description:**
Im Menü Settings -> Apps -> Manage apps -> Android System -> Notifications unter Notification categories taucht der Punkt USB-Verbindung 2x auf. Habe dann zur Kontrolle bei mir die Systemsprache auf Englisch umgestellt und da steht dann 1x  USB-Verbindung und 1x USB connection, s. Screenshot. Wo kommt der deutsche Text in der englischen Übersetzung her? Habe jetzt mal 2 Strings in der framework-res.apk wörtlich übersetzt: USB connected > USB verbunden ("usb_storage_notification_title" und "usb_storage_title", https://github.com/berlinux2016/MIUI11/commit/73fd12e6770af1e0e15670e8c9c7ba2bc7610e51). Glaube aber irgendwie nicht, dass einer davon damit zusammenhängt. Warum sollten deren deutscher Text in der englischen Übersetzung auftauchen?
![Fehler Benachricht](https://user-images.githubusercontent.com/22425869/66266277-e4670680-e822-11e9-9e91-645fab50328c.jpg)

**Comment by Henry2o1o** [comment]
bei mir steht da nur 1x  USB connection

**Comment by MeiGuddet** [comment]
Seltsam.

**Comment by Henry2o1o** [comment]
passt auch von der alphabetischen Reihenfolge her nicht

**Comment by Henry2o1o** [comment]
![image](https://user-images.githubusercontent.com/6131799/66267307-8c82cc80-e82f-11e9-9a21-7803545aa3ff.png)

**Comment by Henry2o1o** [comment]
mal den Cache bereinigen

**Comment by MeiGuddet** [comment]
Bereits mehrfach gemacht.

**Comment by Henry2o1o** [comment]
xiaomi.eu?

**Comment by MeiGuddet** [comment]
Ja klar, sonst würde ich das hier ja nicht posten.

**Comment by Henry2o1o** [comment]
Ja ich habe die selben Strings, aber nicht die Xiaomi.eu 😁

**Comment by Henry2o1o** [comment]
Also könnte es ein Bug sein?

**Comment by MeiGuddet** [comment]
Kein Ahnung, ich versuche ja festzustellen, ob jemand anderes mit der eu-ROM auch diesen Fehler hat. Ich poste das dort mal noch im Forum.

**Comment by Henry2o1o** [comment]
mein Mi Mix (xiaomi.eu) und mein Max3 (MiuiPro) okt, aber mein Note7, da ist das auch so

**Comment by Henry2o1o** [comment]
notification_channel_usb
usb_storage_notification_title
usb_storage_titel

USB-Verbindung

**Comment by Henry2o1o** [comment]
Mix MIUI10, Max3 und Note7 MIUI11

**Comment by freddiN** [comment]
Mi6, Eintrag sehe ich zwei mal in der Liste

**Comment by MeiGuddet** [comment]
9.10.24: Ist immer noch doppelt, finde den Fehler nicht.

**Comment by berlinux2016** [comment]
Kann den Fehler nicht reproduzieren-ist er bei dir weg mit der neuesten Version?

**Comment by freddiN** [comment]
Also bei mir ist der Eintrag immer noch doppelt drin:
![Screenshot_2019-11-20-20-59-36-670_com android settings](https://user-images.githubusercontent.com/14030572/69273562-e15c8580-0bd8-11ea-94ae-92fe5d8b4780.jpg)

MI6, 9.11.14

**Comment by MeiGuddet** [comment]
Bei mir ist er auch noch doppelt drin. Keine Ahnung, wieso. Auch 9.11.14.

**Comment by Henry2o1o** [comment]
ich schicke das Screenshot Mal an MIUI, macht mal noch eins in englisch

**Comment by MeiGuddet** [comment]
Mi 9T
![Screenshot_2019-11-20-21-44-35-069_com android settings](https://user-images.githubusercontent.com/22425869/69276735-474c0b80-0bdf-11ea-908e-fccb73a31498.jpg)

**Comment by Henry2o1o** [comment]
2 sprachig 😂

**Comment by MeiGuddet** [comment]
Ja, voll gaga.

**Comment by Henry2o1o** [comment]
mein Redmi Note 7 , 9.11.14

![image](https://user-images.githubusercontent.com/6131799/69277043-d78a5080-0bdf-11ea-885e-5b846523db01.png)

**Comment by Henry2o1o** [comment]
> ich schicke das Screenshot Mal an MIUI, macht mal noch eins in englisch
> 
> Mi 9T & Mi 6 & Redmi Note 7

erledigt, Mal sehen... 🤔

**Comment by MeiGuddet** [comment]
@ingbrzy @Igor Eisberg: Do you know, where this double entry "USB-Verbindung" came from? To find in Settings -> Apps -> Manage apps -> Android System -> Notifications. It is even to see, when you switch to English language. I am out of ideas where to search for it.

**Comment by berlinux2016** [comment]
@MeiGuddet kannst du nochmal deine Hardware/Software Settings posten. Ich bekomme den Fehler auf keinen meiner Testgeräte.

**Comment by Henry2o1o** [comment]
@berlinux2016 
beim Max 3 ist das nicht so, aber beim meinem Redmi Note 7, eu 9.11.28
![image](https://user-images.githubusercontent.com/6131799/69959074-898e1a80-1506-11ea-90d0-69a518262e52.png)

**Comment by Henry2o1o** [comment]
![photo_2019-12-02_13-28-49](https://user-images.githubusercontent.com/6131799/69960248-47b2a380-1509-11ea-8204-f88ec6e92566.jpg)

**Comment by Henry2o1o** [comment]
![photo_2019-12-02_13-28-49](https://user-images.githubusercontent.com/6131799/69960395-9f510f00-1509-11ea-9f72-cf94a0fe52ad.jpg)

**Comment by Henry2o1o** [comment]
![photo_2019-12-02_13-28-49](https://user-images.githubusercontent.com/6131799/69960556-0a9ae100-150a-11ea-963c-be815d6a239f.jpg)

**Comment by Henry2o1o** [comment]
Auf dem Max 3 ist Pro🤔

**Comment by MeiGuddet** [comment]
> 
> 
> @MeiGuddet kannst du nochmal deine Hardware/Software Settings posten. Ich bekomme den Fehler auf keinen meiner Testgeräte.

Was meinst du mit Hardware/Software Settings? Steh' grad auf'm Schlauch.

**Comment by berlinux2016** [comment]
ok das meinte ich.
Kannst du deine Installation mal in folgenden Schritten machen:

Fastboot Image von Xiaomi verwenden:
http://bigota.d.miui.com/V11.0.3.0.PFJEUXM/davinci_eea_global_images_V11.0.3.0.PFJEUXM_20191116.0000.00_9.0_eea_ef548f28c4.tgz

Danach ins twrp und format Werksreset.

Neueste MIUI eu Rom installieren.

Dann bitte nochmal posten der Fehler müsste dann weg sein.

**Comment by Henry2o1o** [comment]
Manchmal hilft da schon eine Neuinstallation/Clean, hatte auch schon ähnliche Probleme.

**Comment by Henry2o1o** [comment]
Mit Swift Backup alles sichern. Titanium spinnt seit längerer Zeit.
Dann geht das Recht zügig ohne wieder alles bei zu installieren.

**Comment by MeiGuddet** [comment]
Boah. Einen Clean Flash kann ich während der Woche nicht machen, keine Zeit und keine Nerven dafür, geht frühestens am WE. Und da mein Gerät nicht gerootet ist, funktioniert Swift Backup wohl nicht richtig. Muss ich mir was anderes überlegen.

**Comment by Henry2o1o** [comment]
Sichern & Wiederherstellen sollte auch funktionieren / Lokale Sicherung / Sicherung /Sichern System und Apps/Daten.

**Comment by MeiGuddet** [comment]
Das mache ich vor jedem Flash, hab's bisher noch nie gebraucht, weiß also nicht, ob es wirklich funktioniert. In TWRP sichere ich auch immer. Egal, muss warten bis zum WE.

**Comment by Henry2o1o** [comment]
@MeiGuddet 
Root wäre ja kein Problem, lässt sich ja wieder entfernen.

**Comment by Henry2o1o** [comment]
Ich hatte bei einem Versionswechsel auch schon Sachen da stehen , die da nicht hingehören.

**Comment by Henry2o1o** [comment]
Cache und Cache Dalvik schon mal gelöscht?

**Comment by MeiGuddet** [comment]
Wie oben schon geschrieben mehrfach.

**Comment by MeiGuddet** [comment]
Hatte gestern frei und erst mal klein angefangen: Factory Reset auf der eu-ROM ohne Umweg über die Original-ROM. Fehler ist jetzt behoben, kein doppelter Eintrag mehr. Issue geschlossen.
Danke für den Tip @berlinux2016 und @Henry2o1o

**Comment by MeiGuddet** [comment]
> 
> 
> Mi6, Eintrag sehe ich zwei mal in der Liste

Versuch es auch mal mit einem Factory Reset.
