### ISSUE TITLE
MiuiPackageInstaller.apk

### ISSUE THREAD

**Issue by Henry2o1o** [berlinux2016/MIUI11#14]
" ist wohl das Problem?

```
 <string name="settings_warning_dialog_detail">"You'll be prompted in the following cases:
 "&lt;li&gt;When an app contains viruses.&lt;/li&gt;"
 "&lt;li&gt;Installation package comes from an unknown source.&lt;/li&gt;</string>
```
```
<string name="settings_warning_dialog_detail">"In den folgenden Fällen werden Sie gefragt:
"&lt;li&gt;Wenn eine App Viren enthält.&lt;/li&gt;"
"&lt;li&gt;Das Installationspaket stammt aus einer unbekannten Quelle.&lt;/li&gt;</string>
```

![image](https://user-images.githubusercontent.com/6131799/70373737-3c85bc00-18eb-11ea-8f0a-d40e02daba0e.png)

**Comment by MeiGuddet** [comment]
Muss doch normalerweise so aussehen:

> <string name="settings_warning_dialog_detail">"In den folgenden Fällen werden Sie gefragt:
&lt;li&gt;Wenn eine App Viren enthält.&lt;/li&gt;
&lt;li&gt;Das Installationspaket stammt aus einer unbekannten Quelle.&lt;/li&gt;"</string>

**Comment by Henry2o1o** [comment]
ja, das denke ich auch, viel mir gleich auf

**Comment by Henry2o1o** [comment]
![image](https://user-images.githubusercontent.com/6131799/70374224-9c329600-18f0-11ea-9f16-6352a1862385.png)

die Russen dekompilieren nicht, um die Sprachen einzufügen

**Comment by MeiGuddet** [comment]
Soll heißen?

**Comment by Henry2o1o** [comment]
das bei denen trotzdem 6x >"< zu viel sind

**Comment by Henry2o1o** [comment]
![image](https://user-images.githubusercontent.com/6131799/70374424-334c1d80-18f2-11ea-80e5-547a19a7c900.png)

**Comment by Henry2o1o** [comment]
habe die Apk mal dekompiliert, da sieht das jetzt so aus

```
<string name="settings_warning_dialog_detail">"In den folgenden Fällen werden Sie gefragt:
&lt;li>Wenn eine App Viren enthält.&lt;/li>
&lt;li>Das Installationspaket stammt aus einer unbekannten Quelle.&lt;/li>"</string>
```

**Comment by Henry2o1o** [comment]
die Apk auf dem Telefon geöffnet

![image](https://user-images.githubusercontent.com/6131799/70374557-229ca700-18f4-11ea-8d7a-c9499b39f93c.png)

**Comment by Henry2o1o** [comment]
so

**Comment by Henry2o1o** [comment]
settings.apk

```
  <string name="master_clear_desc">"Alle Daten in Ihrem <b>internen Speicher</b> werden gelöscht, inkl.:
&lt;li&gt;Ihr Google Konto&lt;/li&gt;
&lt;li&gt;System- und App-Daten sowie Einstellungen&lt;/li&gt;
&lt;li&gt;Heruntergeladene Apps&lt;/li&gt;"</string>
```

**Comment by Henry2o1o** [comment]
einfach so probieren ...

**Comment by Henry2o1o** [comment]
![image](https://user-images.githubusercontent.com/6131799/70374843-aad07b80-18f7-11ea-97be-2e7fc40a3176.png)


<string name="settings_warning_dialog_detail">"Ще бъдете предупредени в следните случаи:
 "<li>Когато приложението съдържа вируси.</li>"
 "<li>Когато в нашият магазин за приложения е налична по-нова версия.</li>"
 "<li>Когато инсталационният пакет идва от неизвестен източник.</li></string>

**Comment by Henry2o1o** [comment]
![image](https://user-images.githubusercontent.com/6131799/70375283-3d731980-18fc-11ea-9513-ead0f87fb028.png)

```
<string name="settings_warning_dialog_detail">"In den folgenden Fällen werden Sie gefragt:
 "<li>Wenn eine App Viren enthält.</li>"
 "<li>Wenn eine neuere Version einer App in unserem Markt verfügbar ist.</li>"
 "<li>Das Installationspaket stammt aus einer unbekannten Quelle.</li>"</string>
```
