### ISSUE TITLE
Calculator app force close

### ISSUE THREAD

**Issue by 2mali** [berlinux2016/MIUI11#16]
- **MIUI Version:** Miui 11.2 by xiaomi.eu 20.2.20
- **Device name:** Mi 9

**Screenshot/Description:**
Calculator app force close in chapter "age" (Alter) and "home loan" (Hauskredit) only in german language. In english (uk) works without issues.

**Comment by Henry2o1o** [comment]
fixed

**Comment by Henry2o1o** [comment]
![image](https://user-images.githubusercontent.com/6131799/75090098-e4f90300-555f-11ea-8be3-16ca72d94cfd.png)

![image](https://user-images.githubusercontent.com/6131799/75090101-e9252080-555f-11ea-861d-fd648947be25.png)
