### ISSUE TITLE
Diverse 

### ISSUE THREAD

**Issue by Michiiib3** [berlinux2016/MIUI11#19]
Nach gedrückt halten auf ein app symbol, App info, Anfragen, Zahnrad, Standort. Wird dort falsch geschrieben. 
Sowie Kamera App, oben die drei Striche, da steht neigen. Gemeint ist aber Unschärfe. 

- **MIUI Version:** X.X.X
- **Device name:** Mi XYZ

**Screenshot/Description:**

**Comment by Michiiib3** [comment]
Version ist 20.3.28 auf mi 10 pro

**Comment by Henry2o1o** [comment]
> Nach gedrückt halten auf ein app symbol, App info, Anfragen, Zahnrad, Standort. Wird dort falsch geschrieben.
was wird dort falsch geschrieben, Screenshot bitte

**Comment by Henry2o1o** [comment]
config_name_tilt = neigen

移轴 - Shift axis - Achse verschieben - Neigen

**Comment by Michiiib3** [comment]
Siehe Screenshots 

> > Nach gedrückt halten auf ein app symbol, App info, Anfragen, Zahnrad, Standort. Wird dort falsch geschrieben.
> > was wird dort falsch geschrieben, Screenshot bitte

![IMG_20200509_132800](https://user-images.githubusercontent.com/65068089/81472539-f1086e80-91f8-11ea-9efb-8e5dc79d3c12.jpg)
![IMG_20200509_132709](https://user-images.githubusercontent.com/65068089/81472541-f1a10500-91f8-11ea-9b19-5eb671d5674c.jpg)

**Comment by Henry2o1o** [comment]
Standort wurde schon behoben

config_name_tilt = Neigen

移轴 - Shift axis - Achse verschieben - Neigen

es ist schon die Unschärfe, aber wie diese Angezeigt wird, steht da geschrieben, 

als Kreis, 

Parallel und Neigen ist nicht ganz ok, 

Parallel = Waagerecht, oben und unten unscharf
Neigen = Senkrecht, links und rechts unscharf

**Comment by Henry2o1o** [comment]
getestet
Unscharf = keine Unschärfe
Kreis = Unschärfe außen herum
Parallel = parallele Unschärfe, entweder horizontal oder vertikal

**Comment by Henry2o1o** [comment]
![image](https://user-images.githubusercontent.com/6131799/81473582-b35b1400-91ff-11ea-88e8-7adb486c2d77.png)

**Comment by Michiiib3** [comment]
Ja sieht super aus.
Wobei gerade halten mehr wie eine Anweisung klingt als eine Funktion. In der global heißt es Ausrichten. Klingt aber irgendwie auch nicht besser.

**Comment by Henry2o1o** [comment]
@Michiiib3 
kleiner Hinweis noch, Miui11 ist down 😉, da wird nichts mehr geändert 🤷‍♂️

**Comment by Michiiib3** [comment]
Ja ich weiß. Aber miui 12 ist mir noch zu instabil. 😀

**Comment by Henry2o1o** [comment]
> Ja ich weiß. Aber miui 12 ist mir noch zu instabil. 😀

davon habe ich bis jetzt noch nichts bemerkt

**Comment by ganego** [comment]
MIUI 11.0.10.

- Wenn man in den Standardapps nichts für "Telefon" ausgewählt hat (war bei mir nicht der Fall, kA warum) und dann versucht einen Code einzugeben (`*#*#...#*#*`) kommt der Fehler `Vorgang abgelehnt: Keine Standardverbindung` https://github.com/berlinux2016/MIUI11/blob/master/German/main/Contacts.apk/res/values-de/strings.xml#L1142   

So, was möchte der Autor uns sagen? Keine Ahnung. Ergibt keinen Sinn.

Englisch `Couldn't complete action. This isn't your default dial pad.` ist da schon sinnvoller und lässt darauf schließen, dass das benutzte dial pad nicht als Standard eingestellt ist (warum auch immer das für Android wichtig ist).

Kurzum: Übersetzung ändern in z.B. `Vorgang abgelehnt: Aktuelle Wähltastenapp ist nicht als Standard gesetzt`.

**Comment by Henry2o1o** [comment]
Ok, korrigiert.
