### ISSUE TITLE
Kontextmenü

### ISSUE THREAD

**Issue by ExtpumaJl** [berlinux2016/MIUI11#2]
Kontextmenü-Eintrage überlapen sich (siehe Screenshot). Ist es möglich die Einträge "Automatisch ausfüllen" und "Häufig verwendete Sätze" zu kürzen, z.B. "Autom. ausfüllen" und "Häufige Sätze" bzw. "Häufig verw. Sätze"? 

- **MIUI Version:** 9.9.27
- **Device name:** Mi 9

**Screenshot/Description:**
![Screenshot_2019-10-06-17-57-17-266_com miui home](https://user-images.githubusercontent.com/425377/66272032-e81b7d00-e864-11e9-9c5a-93044fd1c6a8.jpg)

**Comment by Henry2o1o** [comment]
Ja, das geht.

**Comment by ExtpumaJl** [comment]
Wäre super. Vielen Dank.

**Comment by Henry2o1o** [comment]
AuswählenAlle auswählenEinfügenAutomatisch ausfüllenHäufig verwendete Sätze
Auswählen Alle auswählen Einfügen Autom. ausfüllen Häufig verw. Sätze

**Comment by ExtpumaJl** [comment]
Einverstanden. Ich berichte dann, wie es im nächsten Build aussieht.
Danke.

**Comment by Henry2o1o** [comment]
Ist das gleiche wie hier auch.
https://github.com/berlinux2016/MIUI11/issues/3

**Comment by ExtpumaJl** [comment]
Es sieht jetzt endlich gut aus. Danke.
![Screenshot_2019-10-11-19-44-32-286_com miui home](https://user-images.githubusercontent.com/425377/66672897-aec97f80-ec5f-11e9-8806-4780b3c251bc.jpg)
