### ISSUE TITLE
Buttons in App-Eigenschaften

### ISSUE THREAD

**Issue by ExtpumaJl** [berlinux2016/MIUI11#3]
Die Namen der Buttons in App-Eigenschaften sind etwas lang, so als ob diese drei einen Satz bilden: Beenden erzwingenDeinstallierenDaten löschen (siehe Screenshot).
Mein Vorschlag: Beenden  Deinst. Daten löschen.
Oder ist das ein Bug in MIUI?

- **MIUI Version:** 9.9.27
- **Device name:** Mi 9

**Screenshot/Description:**
![Screenshot_2019-10-06-19-21-06-674_com miui securitycenter](https://user-images.githubusercontent.com/425377/66272922-ab08b800-e86f-11e9-884f-43cb0deecbdd.jpg)

**Comment by Henry2o1o** [comment]
Ist Geräteabhängig ( Auflösung) und im englischen sonst eh viel kürzer.

![image](https://user-images.githubusercontent.com/6131799/66273118-55cda600-e871-11e9-9b95-73d3ae429354.png)

**Comment by ExtpumaJl** [comment]
Schade. Auf dem Mi 9 sieht es richtig bescheuert aus.

**Comment by Henry2o1o** [comment]
> Schade. Auf dem Mi 9 sieht es richtig bescheuert aus.

Wieviel Zoll hat das denn?

**Comment by ExtpumaJl** [comment]
6,39

**Comment by Henry2o1o** [comment]
![image](https://user-images.githubusercontent.com/6131799/66273277-c1fcd980-e872-11e9-88ba-9bbfda5efc4f.png)

Note 7, 6,3" 2340x1080

**Comment by Henry2o1o** [comment]
![image](https://user-images.githubusercontent.com/6131799/66273348-5ebf7700-e873-11e9-8a2a-9f14bbcf3974.png)

Mi Mix, 6,4", 2040x1080

**Comment by Henry2o1o** [comment]
> 6,39

**Comment by Henry2o1o** [comment]
sorry, falsche taste 😁

> 6,39

was hast du eingestellt/verstellt, auf meinem 6,3er passt das doch

**Comment by ExtpumaJl** [comment]
Mit der Schrift in der XS-Größe sieht es besser aus. Aber der Rest in der UI viel zu klein xD

**Comment by Henry2o1o** [comment]
Ja, das liegt an MIUI11 Beta, da gibt es noch viele Baustellen.

**Comment by ExtpumaJl** [comment]
Dann warte ich, bis es von Xiaomi gelöst wird (<1 Jahr xD )

**Comment by Henry2o1o** [comment]
Ist halt eine MIUI11 Beta 😉

**Comment by MeiGuddet** [comment]
Statt "Beenden erzwingen" können wir "Stopp erzwingen" schreiben.

**Comment by Henry2o1o** [comment]
Bevor wir alles verstümmeln, würde ich erst einmal auf weitere Versionen warten.

**Comment by Henry2o1o** [comment]
https://github.com/berlinux2016/MIUI11/commit/35905ec7d6a5a3cd16eb7337f1099072a3693224

**Comment by ExtpumaJl** [comment]
Es ist immer noch so wie vorhin. Dann bleibt nur zu warten bis Xiaomi es gefixt hat, ein Jahr oder so :D
![Screenshot_2019-10-11-19-48-47-167_com miui securitycenter](https://user-images.githubusercontent.com/425377/66673115-36af8980-ec60-11e9-8100-cd03f5f84f33.jpg)

**Comment by ExtpumaJl** [comment]
Hallo,
also ich vermute es ändert sich nichts hier, da auf Englisch die Buttons in Ordnung sind, selbst mit langen Namen:
![Screenshot_2019-10-20-10-10-42-122_com miui securitycenter](https://user-images.githubusercontent.com/425377/67159067-fb881700-f33f-11e9-95a4-1dfeb858c810.jpg)
Daher aus meiner Sicht wäre folgende Änderung notwendig: Beenden | Deinst. | Daten löschen
Aber die Entscheidung bleibt natürlich euch überlassen.

**Comment by Henry2o1o** [comment]
Da hat sich bisher noch keiner beschwert. 3 versch. Geräte.

![image](https://user-images.githubusercontent.com/6131799/67160034-853de180-f34c-11e9-9f3e-64920139c36f.png)

![image](https://user-images.githubusercontent.com/6131799/67160036-8a029580-f34c-11e9-92c8-d3106156d2f6.png)

![image](https://user-images.githubusercontent.com/6131799/67160040-8e2eb300-f34c-11e9-88f4-9677880752b2.png)

**Comment by Henry2o1o** [comment]
Ich schreibe mal an MIUI bevor wir hier noch mehr verstümmeln.

**Comment by MeiGuddet** [comment]
Bei mir passt es so auch.

**Comment by ExtpumaJl** [comment]
Danke für eure Antworten.
Ich denke, wird Xiaomi an der Stelle nichts in China Devs ändern, da deutsche Sprache in der Variante nicht vorhanden ist und auf Englisch ist da alles ok. Interessant wie es bei Mi 9 in Global Stable aussieht...

**Comment by Henry2o1o** [comment]
vielleicht lässt sich der Abstand irgendwo anpassen

**Comment by Henry2o1o** [comment]
> Danke für eure Antworten.
> Ich denke, Xiaomi wird an der Stelle nichts in China Devs ändern, da deutsche Sprache in der Variante nicht vorhanden ist und auf Englisch ist da alles ok. Interessant wie es bei Mi 9 in Global Stable aussieht...

ich schau mal...

**Comment by ExtpumaJl** [comment]
Das Wort "Abbrechen" scheint auch zu groß zu sein XD
![Screenshot_2019-10-21-08-25-36-541_com miui securitycenter](https://user-images.githubusercontent.com/425377/67181301-7ef74600-f3dc-11e9-9e2f-fb60945e8aad.jpg)

**Comment by Henry2o1o** [comment]
Wir können ja jetzt nicht alles abkürzen, da gibt es noch viel mehr, was zu lang ist. 
Die müssten halt mit mehr 9.png's arbeiten.

**Comment by ExtpumaJl** [comment]
Bei Google scheint alles zu passen, selbst bei langen Namen:
![Screenshot_2019-10-21-15-11-06-432_com miui securitycenter](https://user-images.githubusercontent.com/425377/67208115-3445f000-f415-11e9-952e-32b6e4f7f896.jpg)

**Comment by Henry2o1o** [comment]
passt ja auch nicht, deinstallie...

**Comment by ExtpumaJl** [comment]
Ich meine den Abstand zwischen den Buttons ist anders als bei den Apps auf den von mir geposteten Screenshots. Ist aber nur bei Google und Google Play so, da diese vorinstalliert sind.

**Comment by Henry2o1o** [comment]
stimmt, das ist seltsam, Miui Bug

ist bei mir noch breiter

![image](https://user-images.githubusercontent.com/6131799/67231690-1f328680-f440-11e9-88c5-1d0b55d5b8fb.png)

**Comment by Henry2o1o** [comment]
Hier noch was zum Thema abkürzen 🤣

![image](https://user-images.githubusercontent.com/6131799/67234411-640cec00-f445-11e9-8479-c4eff91493a1.png)

**Comment by Henry2o1o** [comment]
ist halt MIUI11, da gibt es noch viele Baustellen...

**Comment by ExtpumaJl** [comment]
Übrigens, da fehlt die Übersetzung:
![IMG_20191021_215027](https://user-images.githubusercontent.com/425377/67238113-daf9b300-f44c-11e9-8b9f-d1faff83bfb2.jpg)

**Comment by Henry2o1o** [comment]
ja, habe ich mir vorhin schon vermerkt, danke

**Comment by berlinux2016** [comment]
Fixed & closed

**Comment by ExtpumaJl** [comment]
Hm. Gefixt ist es aber nicht, zumindest bei Mi9 :)
![Screenshot_2019-11-01-20-21-35-740_com miui securitycenter](https://user-images.githubusercontent.com/425377/68050340-38abbc00-fce5-11e9-8cc7-d5c7aa2af7fa.jpg)

**Comment by Henry2o1o** [comment]
Bei all meinen Geräten passt das. 
Vielleicht ein Leerzeichen dahinter?

**Comment by ExtpumaJl** [comment]
Was spricht dagegen statt "Stopp erzwingen" einfach "Beenden" zu schreiben? Der Sinn ist doch genau gleich. Dann gibt es zumindest mehr Platz links.

**Comment by Henry2o1o** [comment]
![IMG_20191101_221121_340](https://user-images.githubusercontent.com/6131799/68057005-f25e5900-fcf4-11e9-98bb-b2bcd263be48.jpg)
![IMG_20191101_221119_642](https://user-images.githubusercontent.com/6131799/68057006-f25e5900-fcf4-11e9-8f51-2a6f11b424aa.jpg)

**Comment by Henry2o1o** [comment]
Ich hatte das Problem an MIUI gemeldet, soll wo jetzt behoben wurden sein.

https://ibb.co/xXZJK0T

**Comment by Henry2o1o** [comment]
das liegt am "Dark Mode"

![image](https://user-images.githubusercontent.com/6131799/70860357-0961af00-1f21-11ea-8d0f-9be50a59d0d3.png)

![image](https://user-images.githubusercontent.com/6131799/70860361-0d8dcc80-1f21-11ea-88f8-35780a8e3a1d.png)

**Comment by berlinux2016** [comment]
Closed-nicht durch Translate Team zu fixen
