### ISSUE TITLE
Verbinden & teilen

### ISSUE THREAD

**Issue by danielgoletz** [berlinux2016/MIUI11#4]
- **MIUI Version:** 11
- **Device name:** Mi 9T

**Screenshot/Description:**
Einstellungen Hauptmenü:
Verbinden & teilen
Um die Konsequenz der Großschreibung beizubehalten müsste teilen eigentlich groß geschrieben werden.

**Comment by Henry2o1o** [comment]
Hatte schon mal großgeschrieben, wurde aber wieder geändert.
Geändert 👍
