### ISSUE TITLE
Contacts.apk & Calendar.apk miui bug's?

### ISSUE THREAD

**Issue by Henry2o1o** [berlinux2016/MIUI11#5]
Miui11, alle Sprachen und Geräte

![image](https://user-images.githubusercontent.com/6131799/67166444-c73c4700-f38f-11e9-8054-e5def3d5ac19.png)

Leerzeichen nach Google

**Comment by ExtpumaJl** [comment]
Jep. Habe auch kein Leerzeichen dazwischen.

**Comment by Henry2o1o** [comment]
ja, ich habe eine Lösung bekommen suche aber noch danach

**Comment by Henry2o1o** [comment]
Kalender

![image](https://user-images.githubusercontent.com/6131799/67235090-b569ab00-f446-11e9-8dbe-526498d38590.png)

![image](https://user-images.githubusercontent.com/6131799/67235161-d5996a00-f446-11e9-8821-b9132cf05d8e.png)

![image](https://user-images.githubusercontent.com/6131799/67235177-ddf1a500-f446-11e9-9350-e4664b69f87c.png)

**Comment by Henry2o1o** [comment]
![photo_2019-10-21_21-10-39](https://user-images.githubusercontent.com/6131799/67235455-696b3600-f447-11e9-8153-b55f368519b9.jpg)

so sieht das nach der Änderung aus

**Comment by berlinux2016** [comment]
Fixed & closed
