### ISSUE TITLE
Lautlos-Modus Benachrichtigung

### ISSUE THREAD

**Issue by ExtpumaJl** [berlinux2016/MIUI11#6]
Hallo,
beim Einschalten vom Lautlos-Modus kommt unten die Meldung, dass DND eingeschaltet ist (Zum DND-Modus gewechselt...), es ist aber kein DND-Modus.
- **MIUI Version:** 9.10.17
- **Device name:** Mi 9

**Screenshot/Description:**
![Screenshot_2019-10-22-07-53-44-254_com miui home](https://user-images.githubusercontent.com/425377/67261623-c693d580-f4a1-11e9-8927-2cbbfe1c9522.jpg)

**Comment by Henry2o1o** [comment]
Stimmt

**Comment by Henry2o1o** [comment]
Bei Lautlos und DND kommt der gleiche Hinweis.

**Comment by Henry2o1o** [comment]
Silent Mode ist off
und
In den den Lautlos Modus gewechselt

**Comment by Henry2o1o** [comment]
Glocke

进入静音模式，来电、通知铃声已禁止

Enter silent mode, incoming calls, notification ringtones are forbidden

Aktivieren Sie den Ruhemodus, eingehende Anrufe und Benachrichtigungsklingeltöne sind nicht zulässig

**Comment by Henry2o1o** [comment]
Ich ändere das auf meinen Max 3 und schau mir das hinterher Mal an.

**Comment by Henry2o1o** [comment]
geändert

Glocke
![image](https://user-images.githubusercontent.com/6131799/67265495-285a3c80-f4ae-11e9-8170-e13a3cbb2352.png)

Mond
![image](https://user-images.githubusercontent.com/6131799/67265526-35772b80-f4ae-11e9-8619-0ffc4eb933b8.png)

**Comment by Henry2o1o** [comment]
https://github.com/berlinux2016/MIUI11/commit/1ba463b60aa590a8de49a1a880686dfc41eec850
