### ISSUE TITLE
Gallerie: Momente statt Erinnerungen

### ISSUE THREAD

**Issue by danielgoletz** [berlinux2016/MIUI11#7]
- **MIUI Version:** 11.10.17
- **Device name:** Mi 9

**Screenshot/Description:**
In der Galerie könnte man "Erinnerungen" durch "Momente" ersetzen.
Dies dürfte die Verkürzung verhindern.

**Comment by Henry2o1o** [comment]
ok, teste ich...👍

**Comment by Henry2o1o** [comment]
bei mir jetzt Moment...

**Comment by Henry2o1o** [comment]
![image](https://user-images.githubusercontent.com/6131799/67374171-18f7f380-f581-11e9-95a7-8a0a5590ff26.png)

![image](https://user-images.githubusercontent.com/6131799/67374180-1d241100-f581-11e9-84c1-d8720733d808.png)

**Comment by danielgoletz** [comment]
Das sieht doch viel besser aus :)

**Comment by Henry2o1o** [comment]
😉

**Comment by danielgoletz** [comment]
Wo wir gerade mit der Gallerie.apk zugange sind:

In den Einstellungen: Es sollte "Bestes Foto" heißen statt "Beste Foto"

**Comment by Henry2o1o** [comment]
相似照片优选 - Similar photo preference - ...?

**Comment by Henry2o1o** [comment]
Noch was, versteckte Alben?

**Comment by Henry2o1o** [comment]
Alben sind ja akt. Ordner mit Fotos, ein eig. Album kann man erstellen.

**Comment by berlinux2016** [comment]
Fixed & closed

**Comment by Henry2o1o** [comment]
Der doppelte String-Bug besteht noch!

**Comment by Henry2o1o** [comment]
> Noch was, versteckte Alben?
> 
> 2x Versteckte Alben anzeigen, Bug!
> summary - wäre: Anzeigen und Verwalten versteckter Alben
> ![image](https://user-images.githubusercontent.com/6131799/67423642-eb3c9a00-f5d4-11e9-8952-f858a552ef99.png)
> 
> 开启私密相册 - Open private album - Privates Album öffnen o. halt anzeigen
> 
> Einblenden
> 取消屏蔽 - Unblock - entsperren/anzeigen und sperren/ausblenden
> 
> wenn sie es einblenden/anzeigen

Antwort von MIUI

Also the issue with "View hidden albums" title and summary should be fixed now as well and will be available in next update.

**Comment by Henry2o1o** [comment]
> > Noch was, versteckte Alben?
> > 2x Versteckte Alben anzeigen, Bug!
> > summary - wäre: Anzeigen und Verwalten versteckter Alben
> > ![image](https://user-images.githubusercontent.com/6131799/67423642-eb3c9a00-f5d4-11e9-8952-f858a552ef99.png)
> > 开启私密相册 - Open private album - Privates Album öffnen o. halt anzeigen
> > Einblenden
> > 取消屏蔽 - Unblock - entsperren/anzeigen und sperren/ausblenden
> > wenn sie es einblenden/anzeigen
> 
> Antwort von MIUI
> 
> Also the issue with "View hidden albums" title and summary should be fixed now as well and will be available in next update.

Fehler in  9.11.21 begoben
