### ISSUE TITLE
Einrichtung der App Sperre

### ISSUE THREAD

**Issue by ExtpumaJl** [berlinux2016/MIUI11#8]
Bei der Einrichtung von der App Sperre beim Hinzufügen des Mi-Kontos gibt's es einen Übersetzungsfehler (siehe Screenshot).

- **MIUI Version:** 9.10.17
- **Device name:** Mi 9

**Screenshot/Description:**
![IMG_20191023_203208](https://user-images.githubusercontent.com/425377/67423683-00192d80-f5d5-11e9-9d3b-aa56943908f0.jpg)

**Comment by Henry2o1o** [comment]
ok , geändert

**Comment by Henry2o1o** [comment]
Alle geändert...

**Comment by Henry2o1o** [comment]
Geändert hat sich bei mir nichts, wurde wohl noch nicht übernommen?

**Comment by ExtpumaJl** [comment]
Es hat sich immer noch nichts geändert. Zusätzlich sind noch die Zeichen <u></u>bei Mustersperre dazugekommen:
<u>Sperrmethode ändern</u>
Leider darf da keinen Screenshot machen.

**Comment by Henry2o1o** [comment]
```
  
<string name="password_type_underline">&lt;u&gt;Sperrmethode ändern&lt;/u&gt;</string>
<string name="password_type_underline">&lt;u&gt;Change password       &lt;/u&gt;</string
```>

**Comment by Henry2o1o** [comment]
Xiaomi.eu-MIUIv11-XML-Compare
alles
`&lt;u&gt;....&lt;/u&gt;`

Polnisch
`&lt;u&gt;Zmień hasło&lt;/u&gt;`

miui-decompiled-xml-china
<u>Change password</u>

**Comment by berlinux2016** [comment]
apktools unterstützt html tags nicht. Bitte entfernen aus dem string. #Closed

**Comment by Henry2o1o** [comment]
Aus allen?

**Comment by Henry2o1o** [comment]
9.10.31
`<u>...</u>`
![image](https://user-images.githubusercontent.com/6131799/68068683-bdcfb900-fd57-11e9-8935-ca822e45f348.png)

![image](https://user-images.githubusercontent.com/6131799/68068684-c1634000-fd57-11e9-939e-5cd5530be4a0.png)

**Comment by Henry2o1o** [comment]
9.10.31 dekompiliert
```
    <string name="password_type_underline">&lt;u>Sperrmethode ändern&lt;/u></string>
    <string name="password_type_underline"><u>Change password</u></string>
```

**Comment by Henry2o1o** [comment]
3 Möglichkeiten
</u>
&lt;/u>
&lt;/u&gt;

welche ist nun richtig
